service: swiirl-initiative

projectDir: ../
frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-offline

custom:
  region: ${file(../serverless-config.json):region}
  stage: ${file(../serverless-config.json):stage}
  SwiirlInitiativeAssetsBucketName: ${file(../serverless-config.json):swiirlInitiativeAssetsBucketName}-${self:custom.stage}

provider:
  name: aws
  runtime: nodejs16.x
  region: ${self:custom.region}
  timeout: 15
  stage: ${self:custom.stage}
  profile: default
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    SWIIRL_INITIATIVE_BUCKET: ${self:custom.SwiirlInitiativeAssetsBucketName}
    MY_AWS_ACCESS_KEY_ID: ${env:MY_AWS_ACCESS_KEY_ID}
    MY_AWS_SECRET_ACCESS_KEY: ${env:MY_AWS_SECRET_ACCESS_KEY}
    REGION: ${self:custom.region}

  lambdaHashingVersion: 20201221
  httpApi:
    id: !ImportValue SwiirlHttpApiId-${self:custom.stage}

functions:
  getInitiativeTypes:
    handler: getInitiativeTypes.handler
    events:
      - httpApi:
          path: /v1/initiative-types
          method: get
  create:
    handler: createInitiative.handler
    events:
      - httpApi:
          path: /v1/create-initiative
          method: post
          authorizer:
            type: request
            id: !ImportValue SwiirlGatewayAuthorizerId
  update:
    handler: update.handler
    events:
      - httpApi:
          path: /v1/update-initiative
          method: put
          authorizer:
            type: request
            id: !ImportValue SwiirlGatewayAuthorizerId
  getUserInitiatives:
    handler: getUserInitiatives.handler
    events:
      - httpApi:
          path: /v1/get-user-initiatives
          method: get
  getPresignedURL:
    handler: getPresignedUrl.handler
    events:
      - httpApi:
          path: /v1/get-presigned-urls
          method: post
