service: swiirl-root

projectDir: ../
frameworkVersion: "3"
useDotenv: true

custom:
  region: ${file(../serverless-config.json):region}
  stage: ${file(../serverless-config.json):stage}

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  lambdaHashingVersion: 20201221
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedMethods:
        - GET
        - POST
        - PUT
      allowedHeaders:
        - "*"
    authorizers:
      lambdaAuthorizer:
        type: request
        functionName: lambdaAuthorizer
        enableSimpleResponses: true
        identitySource:
          - $request.header.Authorization

functions:
  root-service:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
          authorizer:
            name: lambdaAuthorizer
  lambdaAuthorizer:
    handler: authorizer.handler

resources:
  Resources:
    SwiirlGatewayAuthorizer:
      Type: AWS::ApiGatewayV2::Authorizer
      Properties:
        Name: SwiirlGatewayAuthorizer
        ApiId: !Ref HttpApi
        AuthorizerType: REQUEST
        AuthorizerPayloadFormatVersion: "2.0"
        EnableSimpleResponses: true
        IdentitySource:
          - $request.header.Authorization
        AuthorizerUri: !Join
          - ""
          - - "arn:"
            - !Ref "AWS::Partition"
            - ":apigateway:"
            - !Ref "AWS::Region"
            - ":lambda:path/2015-03-31/functions/"
            - !Sub "arn:aws:lambda:${self:provider.region}:${aws:accountId}:function:swiirl-root-${self:provider.stage}-lambdaAuthorizer"
            - /invocations
  Outputs:
    SwiirlHttpApiId:
      Description: Id of the HTTP API
      Value: !Ref HttpApi
      Export:
        Name: SwiirlHttpApiId-${self:custom.stage}
    SwiirlHttpApiUrl:
      Description: URL of the HTTP API
      Value: !Join
        - ""
        - - "https://"
          - !Ref HttpApi
          - .execute-api.
          - !Ref "AWS::Region"
          - .
          - !Ref "AWS::URLSuffix"
      Export:
        Name: SwiirlHttpApiUrl-${self:custom.stage}
    SwiirlGatewayAuthorizerId:
      Value: !Ref SwiirlGatewayAuthorizer
      Export:
        Name: SwiirlGatewayAuthorizerId
