service: swiirl-profile

projectDir: ../
frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-offline

custom:
  region: ${file(../serverless-config.json):region}
  stage: ${file(../serverless-config.json):stage}
  SwiirlUserAssetsBucketName: ${file(../serverless-config.json):swiirlUserAssetsBucketName}-${self:custom.stage}
  SwiirlInitiativeAssetsBucketName: ${file(../serverless-config.json):swiirlInitiativeAssetsBucketName}-${self:custom.stage}

provider:
  name: aws
  runtime: nodejs16.x
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  profile: swiirl
  timeout: 15
  environment:
    REGION: ${self:custom.region}
    DB_HOST: ${env:DB_HOST}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    SWIIRL_USER_BUCKET: ${self:custom.SwiirlUserAssetsBucketName}
    SWIIRL_INITIATIVE_BUCKET: ${self:custom.SwiirlInitiativeAssetsBucketName}

  lambdaHashingVersion: 20201221
  httpApi:
    id: !ImportValue SwiirlHttpApiId-${self:custom.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:*
      Resource: "*"

functions:
  update:
    handler: updateProfile.handler
    events:
      - httpApi:
          path: /v1/update-profile
          method: put
  getUser:
    handler: getUser.handler
    events:
      - httpApi:
          path: /v1/users
          method: get
  resetPassword:
    handler: resetPassword.handler
    events:
      - httpApi:
          path: /v1/reset-password
          method: post
